# version: "3.7"
name: "honeycomb"

services:
  honeycomb:
    image: mdlmagistrala/honeycomb:latest
    container_name: honeycomb
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - magistrala-base-net

networks:
  magistrala-base-net:
    driver: bridge
